### ISSUE TITLE
Configurable handling of empty output files

### ISSUE THREAD

**Issue by dansondergaard** [gwforg/gwf#179]
Some tools create an empty file and then write to it, so even if the target fails and nothing is ever written, *gwf* thinks the target has completed (because the file exists). 

I propose that we add a setting, `scheduling.empty_file_mode`, which can take three values:

* `ignore`, activates the current behaviour (no special treatment of empty output files),
* `warn`, shows a warning if *gwf* finds an empty output file,
* `missing`, treat empty files as missing.

I think it would be nice if `missing` was the default, but `ignore` could be the default until we reach 2.0 to avoid surprising users too much.

I think some users `touch` files for various reasons. I don't think these are usually specified in `outputs` and thus are not tracked by *gwf*. But if they are, we could support this use case with another setting: `scheduling.empty_file_exclude`, e.g.:

```
{
    "scheduling.empty_file_mode": "missing", 
    "scheduling.empty_file_exclude": "*.lock"
}
```

will treat empty files as missing, unless they match the `*.lock` pattern.

**Comment by mailund** [comment]
I have used touching files to limit the number of files a workflow checks. I don't think it is that uncommon. I often have some targets that create *lots* of files that I don't want to specify in the workflow--either because I don't know how many they produce a priori or because I just don't want to have to check them and slow down gwf--and there using touch works well.

I think this is a feature that is better set on a per-target level. It can be generalised with having any kind of consistency checks following the completion of a target, but if we do this, it probably shouldn't be checked any time we run a workflow--rather, it should be part of running a target. We could insert a way of checking consistency after a target is run, and update a database with the result.

**Comment by dansondergaard** [comment]
I don't it makes sense to have this on a per-target basis. Your usage scenario is easily supported as long as you name the touched files with e.g. the same suffix:

```
{
    "scheduling.empty_file_mode": "missing", 
    "scheduling.empty_file_exclude": "*.completed"
}
```

You're probably doing this already anyway.

This provides a more consistent user experience and is safer. If an unexpected empty file pops up, it won't go by unnoticed.
