### ISSUE TITLE
Packaging through PyPi

### ISSUE THREAD

**Issue by mittagessen** [gwforg/gwf#195]
I found a long-ago closed ticket about PyPi packaging but that seems to have originated before the great rewrite. Is there any reasoning behind not putting gwf on PyPi? Especially as travis is configured to deploy release but probably fails because no gwf package exists in the PyPi DB.

**Comment by dansondergaard** [comment]
Two reasons:

* The last deploy to PyPI failed and now it won't let me upload new wheels for *gwf*, so I got a bit angry with it and decided to leave it.

* I really, really want people to install *gwf* through conda since I'm trying to encourage the use of environments for scientific projects.

However, if you really want packages on PyPI I'll be happy to make those available too. As you noticed, it's part of the Travis build already, so it's mostly a matter of debugging why it won't let me upload a new wheel.

**Comment by dansondergaard** [comment]
@mittagessen I'll make a package available on PyPI for the next release, so closing this issue.

**Comment by dansondergaard** [comment]
@mittagessen 1.2 has just been released and there's a package on PyPI :-)
