### ISSUE TITLE
Run gwf workflow with user defined inputs

### ISSUE THREAD

**Issue by DanielAndreasen** [gwforg/gwf#263]
I have a use case, where I would like to run my workflow (`gwf run`), but with some additional inputs. This would be something like: `gwf run id16 id42`.
Currently gwf doesn't allow me to do that. Is this a feature you would be interested in being developed (I could try to do it myself and make a PR)?

Alternatively, a plugin could be developed, wich would be something like `gwf prun id16 id42` for "parameter run".

**Comment by dansondergaard** [comment]
I haven't seen a case yet where this was actually necessary. Usually one of these three solutions are perfectly fine:

# Just run a specific target

Most people that request this have a workflow which for example runs the same pipeline for N different samples and they didn't realize that to just run the workflow for one of the samples, they just need to run the final target for that sample only:

```
gwf run FinalAnalysis.Sample89
```

# Environment variables

Pass environment variables to *gwf*, like this:

```
import os

param_one = int(os.environ.get("PARAM1", "42"))
param_two = os.environ.get("PARAM2", "hello"))
```

setting the parameters just become:

```
$ PARAM1=38 PARAM2=world gwf run
```


# Pass in a configuration file

If what you need is configuration, you can do it quite easily:

```
import os
import json

from gwf import Workflow


config_path = os.environ.get("FOO_CONFIG", "config1.json")
config = json.load(open(config_path))

gwf = Workflow()

if config["do_step1"]:
   gwf.target("Step1", inputs=[], outputs=[]) <<< """sleep 10”””    
```

You then run your workflow like this:

```
$ FOO_CONFIG=config2.json gwf run
```

---

Let me know if none of these solutions fit your problem. Otherwise I'll consider the issue closed :-)

**Comment by DanielAndreasen** [comment]
Thanks for the very detailed answer. I still prefer the way as I suggested, but reading from an environment variable(s) seems the simplest way. In my use case it will be something like this (since there can be any number of inputs)

`$ IDS=42,16 gwf run`

and reading it like (not tested yet):

```python
import os

ids = os.environ.get('IDS', '')
if ids and ',' in ids:
    ids = ids.split(',')
elif ids:
    ids = [ids]
```

This will probably be fine. Thanks again. I will close the issue.

**Comment by dansondergaard** [comment]
That's a perfectly fine solution. There's no reason to reimplement something that's been battle-tested for 70+ years :-)
